### ISSUE TITLE
Improve extensions for RandomAccessCollection

### ISSUE THREAD

**Issue by shaps80** [composed-swift/Composed#15]
# Improve extensions for `RandomAccessCollection`

* Author: @shaps80
* Status: **Proposal ([1.1](https://github.com/composed-swift/ComposedUI/milestone/1.1))**

## Introduction

We already provide some enhancements on `ArraySection` to make it behave more like an array. In addition we could add further conformance on `Section` itself using `where` clauses.

E.g. 

```swift
extension Section where Self: RandomAccessCollection {
    public var numberOfElements: Int { return count }
}
```

## Motivation

ComposedMedia sections don't currently conform to the recent updates due to missing auto-conformance. Adding `RandomAccessCollection` conformance to `Section` fixes this and other potential sections in the future.

## Source compatibility

This is an additive feature.

**Comment by shaps80** [comment]
So I was going to do this but felt conflicted about the impact it would have on Single element sections. Thoughts @JosephDuffy ?

**Comment by JosephDuffy** [comment]
[`CollectionOfOne`](https://developer.apple.com/documentation/swift/collectionofone) conforms to `RandomAccessCollection` so while I agree it's not the most logical thing there's precedence.

It might impact API though, if a consumer has already added `RandomAccessCollection` conformance to `Section`?

**Comment by shaps80** [comment]
True but I don't _think_ we can consider all the extensions a consumer might add. Its similar (although I realise not the same) as when we got automatic `Hashable` support in Swift for example, requiring us to delete a lot of code, thankfully!

In this case the consumer's implementation would still be used right?

I also don't know if we have such a huge number of other consumers atm hahah

**Comment by JosephDuffy** [comment]
> In this case the consumer's implementation would still be used right?

I think it errors but I've not tried.
 
> I also don't know if we have such a huge number of other consumers atm hahah

Yeah probably not many, but I don't think it looks great to break semantic versioning.

There are a few little teething issues we've run in to I don't think a 2.0 would be out of the picture, even if we just start with `2.0.0-beta`, `2.0.0-beta.2` etc. for a few releases.

**Comment by shaps80** [comment]
Guess this was never feasible, closing
