### ISSUE TITLE
How to use `ComposedSectionProvider` with `Section`s that update?

### ISSUE THREAD

**Issue by JosephDuffy** [composed-swift/Composed#2]
When calling `ComposedSectionProvider.append(_:)` with a `Section` the `updateDelegate` is not set (and `ComposedSectionProvider` does not conform to `SectionUpdateDelegate`). This causes any updates propagated by the section to not be honoured.

It looks like these updates should be propagated up, performing mapping as required. Does `SectionProviderUpdateDelegate` need to inherit `SectionUpdateDelegate` to ensure these updates are not lost?

**Comment by shaps80** [comment]
Hmm the demo app even adds removes sections without issue. Which wouldn’t be possible if the updateDelegate wasn’t set.

**Comment by JosephDuffy** [comment]
> Hmm the demo app even adds removes sections without issue. Which wouldn’t be possible if the updateDelegate wasn’t set.

Looking at the demo the delegate is set to an instance of `SectionProviderMapping` but I can't find where that's done.

I think I got confused about what it was embedded in. For example I have:

- `ComposedSectionProvider`
  - `ComposedSectionProvider`
    - `ComposedSectionProvider`
      - `SingleElementSection`
      - `SegmentedSectionProvider`
        - `Section`

Changes made to the `Section` are not propagated and the delegate is `nil`, maybe this is actually an issue with `SegmentedSectionProvider`.

I'm still investigating but https://github.com/composed-swift/Composed/blob/master/Sources/Composed/Providers/SegmentedSectionProvider.swift#L91 looks wrong; offsets for `section` will always return `-1`.

**Comment by shaps80** [comment]
I will review this soon and get back to you.

**Comment by shaps80** [comment]
Resolved in #3

**Comment by shaps80** [comment]
This has been resolved and included in release v1.0.3
